# Generated by Django 6.0.3 on 2026-04-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(default='', upload_to='carousel_img/'),
            preserve_default=False,
        ),
    ]
